services:
    zoddo.postmodels.listener:
        class: zoddo\postmodels\event\listener
        arguments:
            - '@zoddo.postmodels.helper'
        tags:
            - { name: event.listener }
    zoddo.postmodels.controller:
        class: zoddo\postmodels\controller\main_controller
        arguments:
            - '@request'
            - '@zoddo.postmodels.helper'
    zoddo.postmodels.helper:
        class: zoddo\postmodels\helper\helper
        arguments:
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@template'
            - '@request'
            - '@controller.helper'
            - '@language'
            - '%core.table_prefix%'
